---
title: "bka_analysis"
output: html_document
---

``` {r,include = FALSE}

wd <- getwd()
source(paste(wd, '/R/soft.max.clean.R', sep = ''))

file_path = '~/Box Sync/Research NSF Bat1Health Collaboration/bat_immunoassays/Evelyn_Data/EB023_BKA_S.aureus_ATCC6538.xlsx'
data <- soft.max.clean(file_path, num_of_time_points = NA)

bka.merge <-  data

data$sample <- tolower(bka.merge$sample)
bka.merge$sample <- gsub(" ", "", bka.merge$sample)

bka.merge$measure <- as.numeric(bka.merge$measure)

```

#BKA Results

##Bacteria Only
###Data Untransformed
``` {r,echo = FALSE}
data <- bka.merge %>%
  filter(experiment_id == '4.26.19_Evelyn Benson') 

data %>%
  unite(well, c(which_row, column)) %>%
  ggplot(aes(x=time, y= (as.numeric(measure)))) +
  #ggplot(aes(x=time, y= log(as.numeric(measure)))) +
  #ggplot(aes(x=time, y= boot::inv.logit(as.numeric(measure)))) +
  geom_point(aes(group = well, col = bacteria)) +
  geom_line(aes(group = well, col = bacteria)) +
  #ylim(.9,2)+
  #xlim(0,.6)+
  facet_grid(~sample)

```












